export * from "./animales.js";
export * from "./inventario-bronze.js";
export * from "./landings.js";
export * from "./pesajes.js";
export * from "./pesajes-bronze.js";
export * from "./tratamientos.js";
export * from "./tratamientos-bronze.js";
export * from "./ventas.js";
export * from "./ventas-bronze.js";
